#!/bin/bash
# Manual testing guide for dashboard

echo "=============================================================================="
echo "DASHBOARD TESTING GUIDE"
echo "=============================================================================="
echo ""
echo "Follow these steps to test the dashboard in Chrome:"
echo ""
echo "Step 1: Run demo script to populate data"
echo "  $ ./scripts/demo.sh"
echo ""
echo "Step 2: Start the API server in one terminal"
echo "  $ cd apps/agent-api"
echo "  $ PYTHONPATH=. .venv/bin/python main.py"
echo ""
echo "Step 3: Start the Next.js dashboard in another terminal"
echo "  $ cd apps/web"
echo "  $ pnpm dev"
echo ""
echo "Step 4: Open Chrome and navigate to:"
echo "  http://localhost:3000"
echo ""
echo "=============================================================================="
echo "WHAT TO TEST:"
echo "=============================================================================="
echo ""
echo "✓ Overview Cards"
echo "  - Total Leads should show 16"
echo "  - Contacted should show 6"
echo "  - Conversions should show 5"
echo "  - Conversion Rate should show ~31%"
echo ""
echo "✓ Pipeline Funnel"
echo "  - Should show visual bars for each stage"
echo "  - Percentages should decrease: 100% → 100% → 37% → 0% → 31%"
echo ""
echo "✓ Experiments Panel"
echo "  - Should show 3 experiments"
echo "  - Each should display α (alpha) and β (beta) values"
echo "  - Thompson Sampling parameters visible"
echo "  - CVR percentages displayed"
echo ""
echo "✓ Experiment Controls"
echo "  1. Click 'Pause' on exp_enterprise_formal_v1"
echo "  2. Verify badge changes to 'Paused' and button says 'Activate'"
echo "  3. Click 'Activate' to re-enable"
echo "  4. Verify it returns to 'Active' status"
echo ""
echo "✓ Activity Feed"
echo "  - Should show recent events with icons"
echo "  - Events like 'New lead', 'scored', 'Outreach sent', 'CONVERTED'"
echo "  - Timestamps should be visible"
echo ""
echo "✓ Auto-refresh"
echo "  - Dashboard should update every 5 seconds"
echo "  - Look for timestamp at bottom updating"
echo ""
echo "=============================================================================="
echo "SCREENSHOT CHECKLIST:"
echo "=============================================================================="
echo ""
echo "For hackathon presentation, capture these screenshots:"
echo ""
echo "1. Full dashboard view showing all sections"
echo "2. Experiment panel zoomed in to show Thompson Sampling parameters"
echo "3. Activity feed showing conversion events (🎉)"
echo "4. Before/after pausing an experiment"
echo ""
