"""add_outreach_templates_and_logs

Revision ID: ac6127a7995f
Revises: 482684b1d498
Create Date: 2025-10-17 12:58:25.728997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6127a7995f'
down_revision: Union[str, Sequence[str], None] = '482684b1d498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('subject_line', sa.String(length=500), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('personalization_prompt', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_templates_experiment_id'), 'outreach_templates', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_outreach_templates_id'), 'outreach_templates', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_templates_template_id'), 'outreach_templates', ['template_id'], unique=True)
    op.create_table('outreach_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('sent_via', sa.String(length=100), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', 'FAILED', name='outreachstatus'), nullable=False),
    sa.Column('status_details', sa.JSON(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['outreach_templates.template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_logs_experiment_id'), 'outreach_logs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_outreach_logs_external_message_id'), 'outreach_logs', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_outreach_logs_id'), 'outreach_logs', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_logs_lead_id'), 'outreach_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outreach_logs_status'), 'outreach_logs', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_logs_template_id'), 'outreach_logs', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_logs_template_id'), table_name='outreach_logs')
    op.drop_index(op.f('ix_outreach_logs_status'), table_name='outreach_logs')
    op.drop_index(op.f('ix_outreach_logs_lead_id'), table_name='outreach_logs')
    op.drop_index(op.f('ix_outreach_logs_id'), table_name='outreach_logs')
    op.drop_index(op.f('ix_outreach_logs_external_message_id'), table_name='outreach_logs')
    op.drop_index(op.f('ix_outreach_logs_experiment_id'), table_name='outreach_logs')
    op.drop_table('outreach_logs')
    op.drop_index(op.f('ix_outreach_templates_template_id'), table_name='outreach_templates')
    op.drop_index(op.f('ix_outreach_templates_id'), table_name='outreach_templates')
    op.drop_index(op.f('ix_outreach_templates_experiment_id'), table_name='outreach_templates')
    op.drop_table('outreach_templates')
    # ### end Alembic commands ###
